# Generated by Django 4.1.7 on 2023-03-29 09:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_names',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='group_names',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='participants',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', ckeditor.fields.RichTextField()),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.group_names')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.participants')),
            ],
        ),
    ]
