# Generated by Django 4.1.7 on 2023-03-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_group_names_added_date_group_names_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='group_names',
            name='group_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='chat.group_type'),
        ),
    ]
