# Generated by Django 4.1.7 on 2023-03-30 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_group_names_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_names',
            name='group_type',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.group_type'),
        ),
    ]
