# Generated by Django 4.1.7 on 2023-03-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_group_names_group_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_type',
        ),
    ]
