# Generated by Django 4.1.7 on 2023-03-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_group_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_names',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='chat.group_category'),
        ),
    ]
