# Generated by Django 4.1.7 on 2023-03-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_participants_village_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='village_group',
        ),
        migrations.AlterField(
            model_name='participants',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
