# Generated by Django 4.1.7 on 2023-03-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Select_school_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.school')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.year')),
            ],
        ),
    ]
