# Generated by Django 4.1.7 on 2023-03-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_year_name_select_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='year',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='year',
            name='status',
        ),
    ]
