# Generated by Django 4.1.7 on 2023-03-31 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_remove_year_added_by_remove_year_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_names',
            name='school',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='chat.school'),
        ),
        migrations.AddField(
            model_name='group_names',
            name='year',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='chat.year'),
        ),
    ]
