# Generated by Django 4.1.7 on 2023-03-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_alter_group_names_school_alter_group_names_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_names',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='chat.school'),
        ),
        migrations.AlterField(
            model_name='group_names',
            name='year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='chat.year'),
        ),
    ]
