# Generated by Django 4.1.7 on 2023-03-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_alter_group_names_school_alter_group_names_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_names',
            name='school',
        ),
        migrations.RemoveField(
            model_name='group_names',
            name='year',
        ),
    ]
