# Generated by Django 4.1.7 on 2023-03-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_remove_group_names_school_remove_group_names_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_names',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.school'),
        ),
    ]
