# Generated by Django 4.1.7 on 2023-03-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_group_names_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_names',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.year'),
        ),
    ]
