# Generated by Django 4.1.7 on 2023-04-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_group_names_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_names',
            name='category',
            field=models.CharField(choices=[('politic', 'politic'), ('village', 'village'), ('education', 'education')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Group_category',
        ),
    ]
