# Generated by Django 4.1.7 on 2023-04-01 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_alter_group_names_category_delete_group_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='select_school_year',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.group_names'),
        ),
        migrations.AlterField(
            model_name='group_names',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.school'),
        ),
        migrations.AlterField(
            model_name='group_names',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.year'),
        ),
    ]
