# Generated by Django 4.1.7 on 2023-04-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_select_school_year_group_alter_group_names_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.group_names')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.participants')),
            ],
        ),
    ]
