# Generated by Django 4.1.7 on 2023-04-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_alter_chat_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='village',
        ),
        migrations.AddField(
            model_name='participants',
            name='village_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
