# Generated by Django 4.1.7 on 2023-04-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_remove_participants_village_participants_village_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='village_id',
        ),
        migrations.AddField(
            model_name='participants',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.group_names'),
        ),
    ]
