# Generated by Django 4.1.7 on 2023-04-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_remove_participants_village_id_participants_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_names',
            name='school',
        ),
        migrations.RemoveField(
            model_name='group_names',
            name='year',
        ),
        migrations.AddField(
            model_name='group_names',
            name='ss_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.school'),
        ),
        migrations.AddField(
            model_name='group_names',
            name='ssc_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group_names'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.participants'),
        ),
        migrations.AlterField(
            model_name='my_group',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group_names'),
        ),
        migrations.AlterField(
            model_name='my_group',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.participants'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.group_names'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Select_school_year',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
