# Generated by Django 4.1.7 on 2023-04-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_remove_group_names_school_remove_group_names_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_names',
            old_name='ss_school',
            new_name='ssc_school',
        ),
    ]
