# Generated by Django 4.1.7 on 2023-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_rename_ss_school_group_names_ssc_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_names',
            name='ssc_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
